version: "3"
services:
  client:
    container_name: muzika_client
    restart: always
    build: client
    ports:
      - 3000:3000
    depends_on:
      - server

  server:
    container_name: muzika_server
    restart: always
    build: server
    ports:
      - 8888:8888
